// Optional LOCAL browser QA via cached @playwright/cli run-code --filename.
// Starts with a fresh page; never visits a remote URL or reads a personal file.
async (page) => {
  const root="C:/Users/yhm19/OneDrive/바탕 화면/2025-2027 서울사이버대 학습 관련/GitHub-Pages-실험/pixel-kitchen/output/playwright";
  const origin=new URL(page.url()).origin;
  const checks=[],errors=[],requests=[];
  const assert=(ok,label)=>{if(!ok)throw new Error(label);checks.push(label);};
  page.on("pageerror",error=>errors.push(error.message));
  page.on("console",message=>{if(message.type()==="error")errors.push(message.text());});
  page.on("request",request=>requests.push(request.url()));
  await page.setViewportSize({width:1440,height:1000});
  await page.reload();
  const settled=()=>page.waitForFunction(()=>!document.querySelector("#run").disabled&&document.querySelector("#result-label").textContent.startsWith("최종"));
  const run=async()=>{await page.getByRole("button",{name:"파이프라인 실행",exact:true}).click();await settled();};
  const kernel=async(values)=>{for(let i=0;i<9;i++)await page.getByRole("spinbutton",{name:`필터 ${Math.floor(i/3)+1}행 ${i%3+1}열`,exact:true}).fill(String(values[i]));await page.getByRole("button",{name:"계수 합을 나누기로",exact:true}).click();};
  const add=async(kind)=>{await page.getByRole("combobox",{name:"추가할 연산",exact:true}).selectOption(kind);await page.getByRole("button",{name:"단계 추가",exact:true}).click();};
  const pass=async(label)=>{await run();assert((await page.locator("#metrics").innerText()).includes("MAE 0.000 · RMSE 0.000"),`${label}: exact computed error`);assert((await page.locator("#feedback").innerText()).includes("충족"),`${label}: objective passed`);};
  await settled();
  assert(await page.locator('#level option[value="4"]').getAttribute("disabled")!==null,"progression initially locked");
  await page.getByRole("spinbutton",{name:"밝기 더하기",exact:true}).fill("6");await run();
  assert((await page.locator("#feedback").innerText()).includes("어두움"),"wrong brightness gets signed feedback");
  await page.getByRole("spinbutton",{name:"밝기 더하기",exact:true}).fill("12");await pass("level 1");
  await page.getByRole("button",{name:"다음 과제 →",exact:true}).click();await settled();
  console.log("SNAPSHOT level 2\n"+await page.locator("#editor").ariaSnapshot());
  assert(!(await page.locator("#presets").isVisible()),"challenge presets hidden");
  await kernel([1,2,1,2,4,2,1,2,1]);await pass("level 2");
  await page.getByRole("button",{name:"다음 과제 →",exact:true}).click();await settled();
  await kernel([1,2,1,2,4,2,1,2,1]);await add("sobel");
  console.log("SNAPSHOT Sobel\n"+await page.locator("#editor").ariaSnapshot());
  await page.getByRole("spinbutton",{name:"증폭",exact:true}).fill("0.5");await pass("level 3");
  await page.getByRole("combobox",{name:"오른쪽 결과",exact:true}).selectOption("0");
  assert((await page.locator("#compare-label").innerText()).includes("오른쪽 1단계"),"intermediate comparison selectable");
  await page.locator("#wipe").focus();await page.keyboard.press("Home");
  assert((await page.locator("#compare-label").innerText()).includes("0%"),"keyboard wipe boundary");
  const coordinate=await page.locator("#coordinate").innerText();
  await page.locator("#result").focus();await page.keyboard.press("ArrowRight");
  assert(coordinate!==await page.locator("#coordinate").innerText(),"keyboard pixel inspector moves");
  assert((await page.locator("#formula").innerText()).includes("Gx="),"Sobel inspector shows gradients");
  await page.getByRole("button",{name:"다음 과제 →",exact:true}).click();await settled();
  await kernel([1,2,1,2,4,2,1,2,1]);await add("threshold");
  await page.getByRole("spinbutton",{name:"문턱값",exact:true}).fill("96");await run();
  assert(!(await page.locator("#feedback").innerText()).includes("충족"),"wrong order fails actual target");
  await page.getByRole("button",{name:"단계 위로",exact:true}).click();await pass("level 4");
  await page.getByRole("button",{name:"다음 과제 →",exact:true}).click();await settled();
  await kernel([1,2,1,2,4,2,1,2,1]);await add("sobel");
  await page.getByRole("spinbutton",{name:"증폭",exact:true}).fill("0.75");await add("threshold");
  await page.getByRole("spinbutton",{name:"문턱값",exact:true}).fill("40");await add("kernel");
  await kernel([0,1,0,0,2,0,0,1,0]);await pass("level 5");
  assert(await page.getByRole("button",{name:"단계 추가",exact:true}).isDisabled(),"four-pass cap UI");
  const metric=await page.locator("#metrics").innerText();await page.locator("#heat-gain").selectOption("16");
  assert(metric===await page.locator("#metrics").innerText(),"heatmap gain does not change error score");
  await page.screenshot({path:root+"/challenge-desktop.png",fullPage:true});
  for(const width of [390,320]){await page.setViewportSize({width,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`no horizontal overflow at ${width}`);await page.screenshot({path:root+`/challenge-${width}.png`,fullPage:true});}
  await page.setViewportSize({width:1440,height:1000});
  await page.getByRole("combobox",{name:"작업 모드",exact:true}).selectOption("lab");await settled();
  console.log("SNAPSHOT lab\n"+await page.locator("#editor").ariaSnapshot());
  await page.getByRole("spinbutton",{name:"나누기",exact:true}).fill("0");await page.getByRole("button",{name:"파이프라인 실행",exact:true}).click();
  assert((await page.locator("#status").innerText()).includes("범위"),"zero divisor rejected");
  assert(await page.getByRole("button",{name:"최종 PNG 저장",exact:true}).isDisabled(),"invalid output cannot export");
  await page.getByRole("spinbutton",{name:"나누기",exact:true}).fill("");await page.getByRole("button",{name:"파이프라인 실행",exact:true}).click();
  assert((await page.locator("#status").innerText()).includes("빈 숫자"),"empty divisor rejected");
  await page.getByRole("button",{name:"순서 초기화",exact:true}).click();
  // Same event turn guarantees cancel races the first yield, independent of CPU speed.
  await page.evaluate(()=>{document.querySelector("#run").click();document.querySelector("#cancel").click();});
  await page.waitForTimeout(80);
  assert((await page.locator("#status").innerText()).includes("취소"),"in-flight calculation cancelled");
  assert(await page.getByRole("button",{name:"최종 PNG 저장",exact:true}).isDisabled(),"cancel cannot publish partial result");
  await run();
  const image=await page.evaluate(()=>{const c=document.createElement("canvas");c.width=4;c.height=2;const ctx=c.getContext("2d"),rgba=new Uint8ClampedArray([12,34,56,255,80,120,160,128,0,0,0,0,255,0,0,255,40,80,120,255,20,40,60,128,0,0,0,0,0,255,0,255]);ctx.putImageData(new ImageData(rgba,4,2),0,0);return c.toDataURL("image/png").split(",")[1];});
  await page.locator("#image-file").setInputFiles({name:"alpha-fixture.png",mimeType:"image/png",buffer:Buffer.from(image,"base64")});await page.waitForFunction(()=>document.querySelector("#dimensions").textContent==="4 × 2");await settled();
  assert((await page.locator("#dimensions").innerText())==="4 × 2","local PNG imported");
  const alpha=await page.evaluate(()=>["original","result"].map(id=>{const c=document.getElementById(id),d=c.getContext("2d").getImageData(0,0,c.width,c.height).data;return [...d].filter((_,i)=>i%4===3);}));
  assert(JSON.stringify(alpha[0])===JSON.stringify(alpha[1]),"imported PNG alpha preserved");
  const downloadPromise=page.waitForEvent("download");await page.getByRole("button",{name:"최종 PNG 저장",exact:true}).click();const download=await downloadPromise;await download.saveAs(root+"/export.png");assert(download.suggestedFilename()==="pixel-kitchen.png","actual PNG download");
  await page.locator("#image-file").setInputFiles({name:"bad.svg",mimeType:"image/svg+xml",buffer:Buffer.from("<svg/>")});assert((await page.locator("#status").innerText()).includes("8 MB"),"unsupported file rejected");
  await page.locator("#image-file").setInputFiles({name:"too-large.png",mimeType:"image/png",buffer:Buffer.alloc(8*1024*1024+1)});assert((await page.locator("#status").innerText()).includes("8 MB"),"oversized file rejected before decode");
  await page.getByRole("button",{name:"샘플 복원",exact:true}).click();await settled();
  assert((await page.locator("#dimensions").innerText())==="600 × 400","sample restore and import reset");
  await page.locator("#wipe").evaluate(el=>{el.value=50;el.dispatchEvent(new Event("input",{bubbles:true}));});
  const sides=await page.evaluate(()=>{const read=(id,x,y)=>[...document.getElementById(id).getContext("2d").getImageData(x,y,1,1).data];return {left:JSON.stringify(read("comparison",10,20))===JSON.stringify(read("original",10,20)),right:JSON.stringify(read("comparison",590,20))===JSON.stringify(read("result",590,20))};});
  assert(sides.left,"wipe left pixels equal original");assert(sides.right,"wipe right pixels equal processed output");
  const comparison=page.locator("#comparison"),position=await comparison.evaluate(el=>({x:el.clientLeft+el.clientWidth*.25,y:el.clientTop+el.clientHeight*.25}));
  await comparison.click({position});assert((await page.locator("#coordinate").innerText())==="x 150 / y 100","fractional viewport pointer selects correct pixel cell");
  assert(requests.every(url=>url.startsWith(origin+"/")),"only local static requests");
  assert(await page.evaluate(()=>localStorage.length===0&&sessionStorage.length===0&&document.cookie===""),"no app persistence");
  assert(errors.length===0,"no console errors / uncaught exceptions");
  return {evidence:"BROWSER_LOCAL Chromium desktop + viewport emulation",count:checks.length,checks,errors,requests};
}
